# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/data.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'Proto/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Proto/data.proto\"J\n\x07request\x12\x11\n\taccountId\x18\x01 \x01(\x04\x12\x13\n\x0b\x63\x61llSignSrc\x18\x02 \x01(\r\x12\x17\n\x0fneedGalleryInfo\x18\x03 \x01(\x08\"@\n\x17\x41\x63\x63ountPersonalShowInfo\x12%\n\nbasic_info\x18\x01 \x01(\x0b\x32\x11.AccountInfoBasic\"s\n\x10\x41\x63\x63ountInfoBasic\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\r\x12\x0b\n\x03\x65xp\x18\x07 \x01(\r\x12\r\n\x05liked\x18\x15 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Proto.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=94
  _globals['_ACCOUNTPERSONALSHOWINFO']._serialized_start=96
  _globals['_ACCOUNTPERSONALSHOWINFO']._serialized_end=160
  _globals['_ACCOUNTINFOBASIC']._serialized_start=162
  _globals['_ACCOUNTINFOBASIC']._serialized_end=277
# @@protoc_insertion_point(module_scope)
