# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PlayerStats.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'PlayerStats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PlayerStats.proto\x12\x0bPlayerStats\"/\n\x07request\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x11\n\tmatchmode\x18\x02 \x01(\r\"\xc3\x01\n\x08response\x12<\n\tsolostats\x18\x01 \x01(\x0b\x32).PlayerStats.AccountInfoWithStatsToClient\x12;\n\x08\x64uostats\x18\x02 \x01(\x0b\x32).PlayerStats.AccountInfoWithStatsToClient\x12<\n\tquadstats\x18\x03 \x01(\x0b\x32).PlayerStats.AccountInfoWithStatsToClient\"\x9c\x01\n\x1c\x41\x63\x63ountInfoWithStatsToClient\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x13\n\x0bgamesplayed\x18\x02 \x01(\r\x12\x0c\n\x04wins\x18\x03 \x01(\r\x12\r\n\x05kills\x18\x04 \x01(\r\x12\x37\n\rdetailedstats\x18\x05 \x01(\x0b\x32 .PlayerStats.PlayerDetailedStats\"\x95\x02\n\x13PlayerDetailedStats\x12\x0e\n\x06\x64\x65\x61ths\x18\x01 \x01(\r\x12\x12\n\ntop10times\x18\x02 \x01(\r\x12\x11\n\ttopntimes\x18\x03 \x01(\r\x12\x19\n\x11\x64istancetravelled\x18\x04 \x01(\r\x12\x14\n\x0csurvivaltime\x18\x05 \x01(\r\x12\x0f\n\x07revives\x18\x06 \x01(\r\x12\x14\n\x0chighestkills\x18\x07 \x01(\r\x12\x0e\n\x06\x64\x61mage\x18\x08 \x01(\r\x12\x11\n\troadkills\x18\t \x01(\r\x12\x11\n\theadshots\x18\n \x01(\r\x12\x15\n\rheadshotkills\x18\x0b \x01(\r\x12\x11\n\tknockdown\x18\x0c \x01(\r\x12\x0f\n\x07pickups\x18\r \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerStats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=34
  _globals['_REQUEST']._serialized_end=81
  _globals['_RESPONSE']._serialized_start=84
  _globals['_RESPONSE']._serialized_end=279
  _globals['_ACCOUNTINFOWITHSTATSTOCLIENT']._serialized_start=282
  _globals['_ACCOUNTINFOWITHSTATSTOCLIENT']._serialized_end=438
  _globals['_PLAYERDETAILEDSTATS']._serialized_start=441
  _globals['_PLAYERDETAILEDSTATS']._serialized_end=718
# @@protoc_insertion_point(module_scope)
